### ISSUE TITLE
Error 405 on address:add

### ISSUE THREAD

**Issue by MikeRalphson** [mailscript/cli#63]
**Describe the bug**
Getting `Unknown status code 405`

**To Reproduce**
1. `mailscript addresses:add --address=[redacted]@mailscript.com`
2. See error

**Expected behavior**
Address to be added or more helpful error message

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04

**Environment (please complete the following information):**
 - NodeJs version `node -v`: 14.15.1
 - NPM version: 6.14.8

**Comment by kanej** [comment]
Hello Mike,

Thanks for opening this issue.

I pushed and released an improved error message that is available if you do a fresh npm install (version mailscript/0.4.20):

![image](https://user-images.githubusercontent.com/24030/110961287-87408000-8347-11eb-9246-5d530b100059.png)

I think the error you are encountering is that in Mailscript you can only add addresses that are off of your mailscript username's subdomain (except the root email address we create automatically - user@mailscript.com), so for my user of `kanej`, valid addresses would be:

* kanej@mailscript.com
* github@kanej.mailscript.com
* trello@kanej.mailscript.com
* junk@kanej.mailscript.com

Does the improved error message cover your issue?

**Comment by MikeRalphson** [comment]
It does, thank you. But I was able to use whatever@myusername.mailscript.com without using the adddress:add functionality, so what does it do?

**Comment by Geo25rey** [comment]
@MikeRalphson whatever@username.mailscript.com forwards to username@mailscript.com by default.

**Comment by MikeRalphson** [comment]
Ah, so does address:add override that default?

**Comment by Geo25rey** [comment]
Yes

**Comment by MikeRalphson** [comment]
Thank you!
